### PR TITLE
Add should as a dependency

### PR DESCRIPTION
**Pull request by ruiquelhas**

### CODE REVIEW

**Comment by ruimarinho** [comment]
@ruiquelhas did you consider the advantages of try/catch and conditionally enable rules if `should` is installed? /cc @fixe @nunofgs

**Comment by ruiquelhas** [comment]
@ruimarinho I think the code gets a bit weird, but I'll create a PR, and we can pick the one we like most.

**Comment by fixe** [comment]
-1 for this approach. I think it should be optional.

**Comment by ruimarinho** [comment]
Refs https://github.com/seegno/jscs-config-seegno/issues/27.

**Pull request closed without merging**
