### PR TITLE
Update dependencies

### LINKED ISSUE #6: Add support for `jscs` 3.x.x

### PR DESCRIPTION
**Pull request by ruiquelhas**
Resolves #6.

### CODE REVIEW

**Comment by ruimarinho** [comment]
There are many breaking changes introduced by this PR due to the bump of jscs to 3.0.0 - @ruiquelhas can you take a deeper look at this by using this branch on authy-client?

E.g. due to object defaults:

```
TypeError: Cannot read property 'replace' of undefined
    at renderLine (authy-client/node_modules/jscs/lib/errors.js:266:16)
```

E.g. due to the use of object spread.

```
internalError: Error running rule validateOrderInObjectKeys: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'name' of undefined
```

```
internalError: Error running rule disallowQuotedKeysInObjects: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'type' of undefined
```

**Comment by ruiquelhas** [comment]
@ruimarinho the first one, at least, seems to be a known [issue](https://github.com/jscs-dev/node-jscs/issues/2219#issuecomment-212653941) and it's apparently related to [esprima](https://github.com/jscs-dev/node-jscs/issues/1130). Maybe we should give up on this entirely, since it's going to be deprecated anytime soon.

**Comment by ruimarinho** [comment]
Agreed, I think it's not worth maintaining this anymore. I'd like the +1 from @fixe and @nunofgs on this, but can you start looking into porting the missing rules in eslint that jscs was covering?

**Comment by fixe** [comment]
+1.

**Pull request closed without merging**
